### ISSUE TITLE
Problems with prefix if no space after comment marker

### ISSUE THREAD

**Issue by GlennOlsson** [repobee/repobee-sanitizer#129]
Tried this with the sanitize file command
```java
//REPOBEE-SANITIZER-START
      return 1;
//REPOBEE-SANITIZER-REPLACE-WITH
      //return -1;
//REPOBEE-SANITIZER-END
```
This failed with 
```
sanitize-file: ERROR
Syntax errors detected in 1 file(s):

File.java
    Line 6: Missing prefix:             // 

```

After some debugging I found that the reason was that there was no space between `//` and `return -1;`. If this is intended, maybe make that clear in the docs?

**Comment by GlennOlsson** [comment]
Nope, seems like this is not all. They seem to have to be on the same indentation. I.e. this worked
```java
    //REPOBEE-SANITIZER-START
    return 1;
    //REPOBEE-SANITIZER-REPLACE-WITH
    // return -1;
    //REPOBEE-SANITIZER-END
```

**Comment by slarse** [comment]
The prefixing is whitespace sensitive. Your first example has `//` as prefix, but then you put `      //` in the replace block. Judging from the first example, this is what you actually want:

```java
//REPOBEE-SANITIZER-START
      return 1;
//REPOBEE-SANITIZER-REPLACE-WITH
//      return -1;
//REPOBEE-SANITIZER-END
```

**Comment by slarse** [comment]
If I recall correctly, the prefixing is entirely literal about the characters. For example, a tab would work fine as a prefix.

**Comment by slarse** [comment]
It might make sense to ignore whitespace for prefixes, it'll be a whole lot easier to get the correct indentation that way. @tohanss wdty? Should be pretty easy, and shouldn't break anything?

**Comment by tohanss** [comment]
I agree, every time I write some code with indentation it feels weird to write like this:

```java
//REPOBEE-SANITIZER-START
      return 1;
//REPOBEE-SANITIZER-REPLACE-WITH
//      return -1;
//REPOBEE-SANITIZER-END
```

partially because I have to make sure that there are exactly the same amount of white-space for the indentation to be correct afterward. I think the way it should work is close to how glen did it the first time, ie:

```java
//REPOBEE-SANITIZER-START
      return 1;
//REPOBEE-SANITIZER-REPLACE-WITH
    //return -1;
or
//    return -1;
//REPOBEE-SANITIZER-END
```

Fixing this will require a bit of work but not more than a few lines worth of code. Notice the difference though, the way I want it is essentially that your prefix is replaced by whitespace (instead of just removed), meaning you can put the code itself exactly where you want it to end up after sanitizing. 

The problem with this however is 
- that the prefix cant be longer than the whitespace before the code. so in the worst case that means no prefix longer than 4 characters (only barbarians use double spaces
- that sanitizer files become incompatible with the old format and will have to be updated

What do you think?

If we want to change this at any point, now is the time! before more courses start using sanitizer. If we don't want to do this, we can still just change it so it doesnt matter where the prefix is

**Comment by slarse** [comment]
> Notice the difference though, the way I want it is essentially that your prefix is replaced by whitespace (instead of just removed), meaning you can put the code itself exactly where you want it to end up after sanitizing.

I don't think that's a good idea. In all editors I know of, it's _very_ easy to align the first non-whitespace character with the indentation, just press tab the desired amount of times. What you propose sounds a inconvenient, because I'd need to indent the stuff to where I want it, and then compensate for the characters I use as a prefix by dedenting.

> that the prefix cant be longer than the whitespace before the code. so in the worst case that means no prefix longer than 4 characters (only barbarians use double spaces

Indentation with tabs says hello! This would bite you right in the behind when palinda comes around :)

I think the best course of action is to just ignore whitespace preceding prefixes. That's also much simpler: just do `line.lstrip()` when looking for prefixes.
